In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("./data_ex_labeled.csv")

In [4]:
df.head()

,Unnamed: 0,Unnamed: 0.1,filename_A,store_A,put_A,wrtmp_A,loadg_A,storeg_A,cas_A,sucessors_A,...,filename_B,store_B,put_B,wrtmp_B,loadg_B,storeg_B,cas_B,sucessors_B,predecessors_B,output
0,0,0,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,...,gcc_coreutils8.31_O3_users,2874,15613,20126,0,0,0,2682,2682,0
1,1,1,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,...,gcc_coreutils8.31_O1_tsort,1365,7281,12269,0,0,0,1879,1879,0
2,2,2,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,...,gcc_coreutils8.31_O1_nice,1116,6156,10512,0,0,0,1588,1588,0
3,3,3,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,...,gcc_coreutils8.31_O1_true,997,5372,9066,0,0,0,1332,1332,0
4,4,4,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,...,gcc_coreutils8.31_O0_sha1sum,2299,11549,25496,0,0,0,2561,2561,0

In [11]:
#df.drop(['Unnamed:0', 'Unnamed:0.1'], axis=1)
df.columns[0:2]
new_df = df.drop(df.columns[0:2], axis=1)

In [12]:
new_df.head()

,filename_A,store_A,put_A,wrtmp_A,loadg_A,storeg_A,cas_A,sucessors_A,predecessors_A,filename_B,store_B,put_B,wrtmp_B,loadg_B,storeg_B,cas_B,sucessors_B,predecessors_B,output
0,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,4757,gcc_coreutils8.31_O3_users,2874,15613,20126,0,0,0,2682,2682,0
1,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,4757,gcc_coreutils8.31_O1_tsort,1365,7281,12269,0,0,0,1879,1879,0
2,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,4757,gcc_coreutils8.31_O1_nice,1116,6156,10512,0,0,0,1588,1588,0
3,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,4757,gcc_coreutils8.31_O1_true,997,5372,9066,0,0,0,1332,1332,0
4,gcc_coreutils8.31_O2_chown,2819,18959,30284,0,0,0,4757,4757,gcc_coreutils8.31_O0_sha1sum,2299,11549,25496,0,0,0,2561,2561,0